# Generated by Django 5.1.3 on 2024-11-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True)),
                ('usuario', models.IntegerField()),
                ('codpos', models.IntegerField(max_length=6)),
                ('ciudad', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userdir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(unique=True)),
                ('direccion', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopat', models.CharField(max_length=30)),
                ('apellidomat', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=25)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(unique=True)),
                ('usuario', models.IntegerField()),
                ('producto', models.IntegerField()),
                ('direccion', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
