# Generated by Django 5.1.3 on 2024-11-17 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_direcciones_userdir_vendedores_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciones',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='codpos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdir',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.direcciones', unique=True),
        ),
        migrations.AlterField(
            model_name='userdir',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.direcciones'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
